# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-stretch

    working_directory: /go/src/github.com/satta/ifplugo
    steps:
      - checkout
      - run: go get -t -v ./...
      - run: go test -v ./...
